export enum EnvConfigEnum {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  TEST_DATABASE = 'TEST_DATABASE',
  DEV_DATABASE = 'DEV_DATABASE',
  PRODUCTION_DATABASE = 'PRODUCTION_DATABASE',
  TOKEN_SECRET = 'TOKEN_SECRET',
  JWT_EXPIRE = 'JWT_EXPIRE',
}
